development:
  adapter: postgresql
  encoding: unicode
  database: elearn_light_development
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

test:
  adapter: postgresql
  encoding: unicode
  database: elearn_light_test

